config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'message' => 'morses#new'

  resources :morses

end

app/models/morse.rb
class Morse < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def hello
    render text: "hello, world!"
  end

end

app/controllers/morses_controller.rb
class MorsesController < ApplicationController
  before_action :set_morse, only: [:show, :edit, :update, :destroy]

  # GET /morses
  # GET /morses.json
  def index
    @morses = Morse.all
  end

  # GET /morses/1
  # GET /morses/1.json
  def show
  end

  # GET /morses/new
  def new
    @morse = Morse.new
  end

  # GET /morses/1/edit
  def edit
  end

  # POST /morses
  # POST /morses.json
  def create
    @morse = Morse.new(morse_params)

    respond_to do |format|
      if @morse.save
        format.html { redirect_to @morse, notice: 'Morse was successfully created.' }
        format.json { render :show, status: :created, location: @morse }
      else
        format.html { render :new }
        format.json { render json: @morse.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /morses/1
  # PATCH/PUT /morses/1.json
  def update
    respond_to do |format|
      if @morse.update(morse_params)
        format.html { redirect_to @morse, notice: 'Morse was successfully updated.' }
        format.json { render :show, status: :ok, location: @morse }
      else
        format.html { render :edit }
        format.json { render json: @morse.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /morses/1
  # DELETE /morses/1.json
  def destroy
    @morse.destroy
    respond_to do |format|
      format.html { redirect_to morses_url, notice: 'Morse was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_morse
      @morse = Morse.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def morse_params
      params.require(:morse).permit(:name, :message)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis
  def full_title(page_title = '')
    base_title = "MorseMe"
    if page_title.empty?
      base_title
    else
      "{page_title} | #{base_title}"
    end
  end

end

app/helpers/morses_helper.rb
module MorsesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
	<%= link_to "MorseMe", root_path %>
		<nav>
			<ul class="nav navbar-nav pull-right">
				<li><%= link_to "Home", root_path %></li>
				<li><%= link_to "About", about_path %></li>
				<li><%= link_to "Message", message_path %></li>
			</ul>
		</nav>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MorseMe</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
  <%= yield %>
  </div>

</body>
</html>

app/views/morses/_form.html.erb
<%= form_for(@morse) do |f| %>
  <% if @morse.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@morse.errors.count, "error") %> prohibited this morse from being saved:</h2>

      <ul>
      <% @morse.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_field :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/morses/edit.html.erb
<h1>Editing Morse</h1>

<%= render 'form' %>

<%= link_to 'Show', @morse %> |
<%= link_to 'Back', morses_path %>

app/views/morses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Morses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @morses.each do |morse| %>
      <tr>
        <td><%= morse.name %></td>
        <td><%= morse.message %></td>
        <td><%= link_to 'Show', morse %></td>
        <td><%= link_to 'Edit', edit_morse_path(morse) %></td>
        <td><%= link_to 'Destroy', morse, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Morse', new_morse_path %>

app/views/morses/new.html.erb
<h1>Send Morse Code</h1>

<div class="container">
<%= form_for(@morse) do |f| %>
	<div class="field">
	<%= f.text_area :message, placeholder: "Send a message..." %>
	</div>
	<%= f.submit "Post", class: "btn btn-primary" %>
<% end %>
</div>

app/views/morses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @morse.name %>
</p>

<p>
  <strong>Message:</strong>
  <%= @morse.message %>
</p>

<%= link_to 'Edit', edit_morse_path(@morse) %> |
<%= link_to 'Back', morses_path %>

app/views/static_pages/about.html.erb
<h1>About MorseMe</h1>
<p>MorseMe is a RaspberryPi hosted web app that allows outsiders to send messages to in morse code.</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron"
	<h1>MorseMe</h1>
	<h2>Raspberry Pi + Rails + Morse Code</h2>
</div>